name: Setup Air Demo
run-name: ${{ github.actor }} is testing out Setup Air Actions🚀
on: [push]
jobs:
  Setup-Air:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install
        uses: posit-dev/setup-air@v1
      - run: echo "💡 The ${{ github.repository }} repository is being checked by Air."
      - name: Check
        run: air format . --check
      - run: echo "🖥️ Checking complete."