name: Setup Air Demo
run-name: ${{ github.actor }} is testing out Setup Air Actions🚀
on: [push]
jobs:
  Setup-Air:
      runs-on: ubuntu-latest
      steps:
      - name: Install
        uses: posit-dev/setup-air@v1
      - name: Check
        run: air format . --check